const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');const statsEl=document.getElementById('stats');const actionsEl=document.getElementById('actions');const panelEl=document.getElementById('panel');const logEl=document.getElementById('log');
const SAVE_KEY='farm_auto_save_v1';const TILE=24;const W=100,H=100;const TICK_RATE=20;const DT=1000/TICK_RATE;const VIEW_MARGIN=2;
const SEEDS=['wheat','corn','carrot'];
const cropDefs={wheat:{name:'Wheat',grow:18,seedCost:2,yield:5,color:'#d4c36a'},corn:{name:'Corn',grow:32,seedCost:6,yield:14,color:'#d8d06a'},carrot:{name:'Carrot',grow:48,seedCost:12,yield:28,color:'#d98a3a'}};
const techDefs=[{id:'robotSpeed',name:'Robot Speed',base:50,mult:1.75,desc:'+10% robot speed per level'},{id:'yieldBoost',name:'Yield Boost',base:80,mult:1.9,desc:'+1 crop yield per level'},{id:'harvestRadius',name:'Harvester Radius',base:120,mult:2,desc:'AI can harvest in 2-tile radius'},{id:'routeSlots',name:'Route Slots',base:150,mult:2.2,desc:'+1 waypoint slot per level'},{id:'automation',name:'Automation',base:220,mult:2.4,desc:'Unlocks more robot logic'}];
const buildingDefs={storage:{name:'Storage',cost:{wood:30,stone:10}},farm:{name:'Farm Plot',cost:{wood:8}},dock:{name:'Dock',cost:{wood:20,stone:5}},conveyor:{name:'Conveyor',cost:{wood:2,stone:1}}};
class Inventory{constructor(data){this.items=data||{gold:50,wood:20,stone:10,seeds:20};}get(k){return this.items[k]||0}add(k,n){this.items[k]=(this.items[k]||0)+n}has(cost){for(const k in cost)if(this.get(k)<cost[k])return false;return true}spend(cost){if(!this.has(cost))return false;for(const k in cost)this.items[k]-=cost[k];return true}}
class Grid{constructor(){this.tiles=new Uint8Array(W*H);this.crop=new Array(W*H).fill(null);this.building=new Array(W*H).fill(null);}idx(x,y){return x+y*W}in(x,y){return x>=0&&y>=0&&x<W&&y<H}get(x,y){return this.tiles[this.idx(x,y)]}set(x,y,v){this.tiles[this.idx(x,y)]=v}}
class Robot{constructor(x,y){this.x=x;this.y=y;this.path=[];this.goal=null;this.mode='idle';this.speed=1;this.carry=0;this.carryType='';this.route=[];this.routeIndex=0;this.wait=0;this.home={x,y};}serialize(){return{ x:this.x,y:this.y,path:this.path,goal:this.goal,mode:this.mode,speed:this.speed,carry:this.carry,carryType:this.carryType,route:this.route,routeIndex:this.routeIndex,wait:this.wait,home:this.home};}}
class Building{constructor(type){this.type=type;this.t=0;}}
const state={grid:new Grid(),inv:new Inventory(),robots:[new Robot(10,10)],camera:{x:0,y:0,zoom:1},selected:'plant-wheat',selectedTile:null,tick:0,acc:0,last:performance.now(),paused:false,tech:{robotSpeed:0,yieldBoost:0,harvestRadius:0,routeSlots:0,automation:0},moneyPerSec:0,autoPlant:true,logs:[],durability:0};
function log(msg){state.logs.unshift(msg);state.logs=state.logs.slice(0,8);logEl.innerHTML=state.logs.map(s=>`<div>${s}</div>`).join('')}
function costForTech(id,lvl){const d=techDefs.find(t=>t.id===id);return Math.floor(d.base*Math.pow(d.mult,lvl))}
function totalTechCost(id){return costForTech(id,state.tech[id]||0)}
function placeInitial(){for(let x=20;x<30;x++)for(let y=20;y<30;y++)state.grid.set(x,y,1);state.grid.building[state.grid.idx(25,25)]={type:'storage'};state.grid.building[state.grid.idx(26,25)]={type:'dock'};for(let i=0;i<4;i++)state.robots.push(new Robot(25+i,27));}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify({grid:[...state.grid.tiles],crop:state.grid.crop,building:state.grid.building,inv:state.inv.items,robots:state.robots.map(r=>r.serialize()),tech:state.tech,camera:state.camera,tick:state.tick,autoPlant:state.autoPlant}))}
function load(){const s=localStorage.getItem(SAVE_KEY);if(!s){placeInitial();return}try{const d=JSON.parse(s);state.grid.tiles=Uint8Array.from(d.grid);state.grid.crop=d.crop;state.grid.building=d.building;state.inv=new Inventory(d.inv);state.robots=d.robots.map(r=>Object.assign(new Robot(r.x,r.y),r));state.tech=d.tech||state.tech;state.camera=d.camera||state.camera;state.tick=d.tick||0;state.autoPlant=d.autoPlant??true}catch(e){placeInitial()}}
function canPlace(x,y){return state.grid.in(x,y)&&!state.grid.building[state.grid.idx(x,y)]}
function neighbors(x,y){return [[x+1,y],[x-1,y],[x,y+1],[x,y-1]].filter(([a,b])=>state.grid.in(a,b))}
function findPath(sx,sy,tx,ty){const q=[[sx,sy]];const prev=new Int32Array(W*H).fill(-1);const seen=new Uint8Array(W*H);seen[state.grid.idx(sx,sy)]=1;let qi=0;while(qi<q.length){const [x,y]=q[qi++];if(x===tx&&y===ty)break;for(const [nx,ny] of neighbors(x,y)){const id=state.grid.idx(nx,ny);if(seen[id])continue;if(state.grid.get(nx,ny)===2)continue;seen[id]=1;prev[id]=state.grid.idx(x,y);q.push([nx,ny])}}const end=state.grid.idx(tx,ty);if(prev[end]===-1&&!(sx===tx&&sy===ty))return [];const path=[];let cur=end;while(cur!==state.grid.idx(sx,sy)){path.push([cur%W,(cur/W)|0]);cur=prev[cur];if(cur<0)break}return path.reverse()}
function assignRoute(robot,route){robot.route=route;robot.routeIndex=0;robot.mode='route'}
function tickRobot(r){r.speed=1+state.tech.robotSpeed*0.1;if(r.wait>0){r.wait--;return}if(r.route.length){const [tx,ty]=r.route[r.routeIndex];if(r.x===tx&&r.y===ty){r.routeIndex++;if(r.routeIndex>=r.route.length){r.route=[];r.routeIndex=0;r.mode='idle'}return}const dx=Math.sign(tx-r.x),dy=Math.sign(ty-r.y);if(dx&&dy&&Math.abs(tx-r.x)===Math.abs(ty-r.y)){}if(Math.random()<0.5?r.x!==tx:r.y!==ty){if(r.x!==tx)r.x+=dx;else r.y+=dy}else{if(r.y!==ty)r.y+=dy;else r.x+=dx}return}let best=null;for(let y=Math.max(0,r.y- state.tech.harvestRadius);y<Math.min(H,r.y+state.tech.harvestRadius+1);y++)for(let x=Math.max(0,r.x-state.tech.harvestRadius);x<Math.min(W,r.x+state.tech.harvestRadius+1);x++){const c=state.grid.crop[state.grid.idx(x,y)];if(c&&c.ready){best={x,y,c};break}}if(best){const p=findPath(r.x,r.y,best.x,best.y);if(p.length){r.path=p;r.goal=best}}if(r.path.length){const [nx,ny]=r.path[0];if(r.x===nx&&r.y===ny)r.path.shift();else{if(r.x<nx)r.x++;else if(r.x>nx)r.x--;else if(r.y<ny)r.y++;else if(r.y>ny)r.y--;return}}if(r.goal&&r.x===r.goal.x&&r.y===r.goal.y){const id=state.grid.idx(r.x,r.y);const c=state.grid.crop[id];if(c&&c.ready){const gain=c.yield+state.tech.yieldBoost;state.inv.add('gold',gain);state.grid.crop[id]=null;state.moneyPerSec+=gain*0.05;log(`Harvested ${c.type}+${gain}`);r.wait=2;return}}if(state.autoPlant){for(let i=0;i<3;i++){const x=(Math.random()*W)|0,y=(Math.random()*H)|0,id=state.grid.idx(x,y);if(state.grid.get(x,y)===1&&!state.grid.crop[id]){const type=SEEDS[(Math.random()*SEEDS.length)|0];const def=cropDefs[type];if(state.inv.get('seeds')>=def.seedCost){state.inv.add('seeds',-def.seedCost);state.grid.crop[id]={type,grow:0,ready:false};break}}}}}
function updateCrops(){for(let i=0;i<state.grid.crop.length;i++){const c=state.grid.crop[i];if(!c)continue;c.grow++;if(c.grow>=cropDefs[c.type].grow)c.ready=true}}
function updateTechIncome(){state.inv.add('gold',Math.floor(state.moneyPerSec/20));state.moneyPerSec*=0.985}
function buyTech(id){const lvl=state.tech[id]||0;const cost=costForTech(id,lvl);if(state.inv.get('gold')<cost)return;state.inv.add('gold',-cost);state.tech[id]=lvl+1;log(`${id} -> ${lvl+1}`)}
function placeBuilding(type,x,y){const d=buildingDefs[type];if(!d||!canPlace(x,y))return;if(!state.inv.spend(d.cost))return;state.grid.building[state.grid.idx(x,y)]={type};}
function draw(){const dpr=devicePixelRatio||1;canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);const cam=state.camera;const startX=Math.max(0,((cam.x- VIEW_MARGIN)/TILE)|0);const startY=Math.max(0,((cam.y- VIEW_MARGIN)/TILE)|0);const endX=Math.min(W,(((cam.x+innerWidth/cam.zoom)/TILE)+VIEW_MARGIN)|0);const endY=Math.min(H,(((cam.y+innerHeight/cam.zoom)/TILE)+VIEW_MARGIN)|0);ctx.save();ctx.scale(cam.zoom,cam.zoom);ctx.translate(-cam.x,-cam.y);for(let y=startY;y<endY;y++)for(let x=startX;x<endX;x++){const id=state.grid.idx(x,y);const t=state.grid.get(x,y);ctx.fillStyle=t===1?'#355d2a':t===2?'#4b4b4b':'#244';ctx.fillRect(x*TILE,y*TILE,TILE-1,TILE-1);const c=state.grid.crop[id];if(c){ctx.fillStyle=cropDefs[c.type].color;ctx.fillRect(x*TILE+4,y*TILE+4,TILE-8,TILE-8);if(c.ready){ctx.fillStyle='#ffd';ctx.fillRect(x*TILE+18,y*TILE+3,4,4)}}const b=state.grid.building[id];if(b){ctx.fillStyle=b.type==='storage'?'#7b4':'#48a';ctx.fillRect(x*TILE+3,y*TILE+3,TILE-6,TILE-6)}}for(const r of state.robots){ctx.fillStyle='#ff6';ctx.fillRect(r.x*TILE+6,r.y*TILE+6,TILE-12,TILE-12);if(r.route.length){ctx.strokeStyle='rgba(255,255,0,.35)';ctx.beginPath();ctx.moveTo(r.x*TILE+12,r.y*TILE+12);for(let i=r.routeIndex;i<r.route.length;i++)ctx.lineTo(r.route[i][0]*TILE+12,r.route[i][1]*TILE+12);ctx.stroke()}}ctx.restore();const inv=state.inv.items;statsEl.innerHTML=`Gold: ${Math.floor(inv.gold||0)} | Seeds: ${inv.seeds||0} | Wood: ${inv.wood||0} | Stone: ${inv.stone||0} | Robots: ${state.robots.length} | Tick: ${state.tick}`;panelEl.innerHTML=`Tool: ${state.selected}\nTech: ${Object.entries(state.tech).map(([k,v])=>`${k}:${v}`).join('  ')}\nAuto-plant: ${state.autoPlant?'on':'off'}\nTip: left-click tiles, mousewheel zoom, drag pan`;}
function loop(t){state.acc+=t-state.last;state.last=t;while(state.acc>=DT){state.tick++;updateCrops();updateTechIncome();for(const r of state.robots)tickRobot(r);state.acc-=DT;if(state.tick%40===0)save()}draw();requestAnimationFrame(loop)}
function buildButtons(){actionsEl.innerHTML='';const tools=[['plant-wheat','Plant Wheat'],['plant-corn','Plant Corn'],['plant-carrot','Plant Carrot'],['robot','Add Robot'],['storage','Storage'],['farm','Farm Plot'],['dock','Dock'],['conveyor','Conveyor']];for(const [id,label] of tools){const b=document.createElement('button');b.textContent=label;b.className=id===state.selected?'sel':'';b.onclick=()=>{state.selected=id;buildButtons();};actionsEl.appendChild(b)}for(const td of techDefs){const b=document.createElement('button');b.textContent=`${td.name} ${state.tech[td.id]||0} (${costForTech(td.id,state.tech[td.id]||0)}g)`;b.onclick=()=>buyTech(td.id);actionsEl.appendChild(b)}const b=document.createElement('button');b.textContent=state.autoPlant?'Auto on':'Auto off';b.onclick=()=>{state.autoPlant=!state.autoPlant;buildButtons()};actionsEl.appendChild(b)}
canvas.addEventListener('mousedown',e=>{const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left)/state.camera.zoom+state.camera.x;const y=(e.clientY-rect.top)/state.camera.zoom+state.camera.y;const gx=Math.floor(x/TILE),gy=Math.floor(y/TILE);if(!state.grid.in(gx,gy))return;if(e.button===1)return;const id=state.grid.idx(gx,gy);if(state.selected==='robot'){state.robots.push(new Robot(gx,gy));return}if(state.selected.startsWith('plant-')){const type=state.selected.split('-')[1];const def=cropDefs[type];if(state.inv.get('seeds')>=def.seedCost&&state.grid.get(gx,gy)===1&&!state.grid.crop[id]){state.inv.add('seeds',-def.seedCost);state.grid.crop[id]={type,grow:0,ready:false}}}else if(buildingDefs[state.selected])placeBuilding(state.selected,gx,gy);else if(state.selected==='conveyor')state.grid.set(gx,gy,2)});
let drag=false,sx=0,sy=0,cx=0,cy=0;canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{const z=state.camera.zoom;state.camera.zoom=Math.max(.5,Math.min(2,z*(e.deltaY>0?.9:1.1)))});canvas.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;sy=e.clientY;cx=state.camera.x;cy=state.camera.y});window.addEventListener('pointerup',()=>drag=false);window.addEventListener('pointermove',e=>{if(!drag)return;state.camera.x=Math.max(0,Math.min(W*TILE-innerWidth/state.camera.zoom,cx-(e.clientX-sx)/state.camera.zoom));state.camera.y=Math.max(0,Math.min(H*TILE-innerHeight/state.camera.zoom,cy-(e.clientY-sy)/state.camera.zoom))});window.addEventListener('keydown',e=>{if(e.key==='s'&&(e.ctrlKey||e.metaKey)){e.preventDefault();save()}if(e.key==='p')state.paused=!state.paused;if(e.key==='r')save()});buildButtons();load();setInterval(()=>{if(!state.paused)save()},5000);requestAnimationFrame(loop);

const ui={startMenu:document.getElementById('startMenu'),shop:document.getElementById('shop'),btnNewGame:document.getElementById('btnNewGame'),btnContinue:document.getElementById('btnContinue'),startHint:document.getElementById('startHint')};
function openStartMenu(show){ui.startMenu.classList.toggle('show',!!show);state.paused=!!show;}
function toggleShop(force){const v=force!==undefined?force:ui.shop.classList.contains('hidden');ui.shop.classList.toggle('hidden',!v);}
function renderShop(){const items=[...Object.entries(buildingDefs).map(([id,d])=>({type:'building',id,label:d.name,cost:d.cost})),...cropDefs?Object.entries(cropDefs).map(([id,d])=>({type:'seed',id,label:d.name,cost:{seeds:d.seedCost}})):[],...techDefs.map(td=>({type:'tech',id:td.id,label:td.name,cost:{gold:costForTech(td.id,state.tech[td.id]||0)}}))];ui.shop.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px"><strong>Shop</strong><button id="closeShop">Schließen</button></div>'+items.map(it=>`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center;margin:8px 0;padding:8px;border:1px solid #334357;border-radius:10px"><div><div><b>${it.label}</b></div><div class="hint">${Object.entries(it.cost).map(([k,v])=>`${v} ${k}`).join(', ')}</div></div><button data-buy="${it.type}:${it.id}">Kaufen</button></div>`).join('');ui.shop.querySelector('#closeShop').onclick=()=>toggleShop(false);ui.shop.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const [type,id]=b.dataset.buy.split(':');if(type==='tech')buyTech(id);else if(type==='seed'){state.inv.add('seeds',10);state.inv.add('gold',-cropDefs[id].seedCost)}else if(type==='building'){state.selected=id;buildButtons()}renderShop();});}
function buildButtons(){actionsEl.innerHTML='';const tools=[['plant-wheat','Plant Wheat'],['plant-corn','Plant Corn'],['plant-carrot','Plant Carrot'],['robot','Add Robot'],['storage','Storage'],['farm','Farm Plot'],['dock','Dock'],['conveyor','Conveyor']];for(const [id,label] of tools){const b=document.createElement('button');b.textContent=label;b.className=id===state.selected?'sel':'';b.onclick=()=>{state.selected=id;buildButtons();};actionsEl.appendChild(b)}const shopBtn=document.createElement('button');shopBtn.textContent='Shop';shopBtn.onclick=()=>{toggleShop(true);renderShop()};actionsEl.appendChild(shopBtn);const b=document.createElement('button');b.textContent=state.autoPlant?'Auto on':'Auto off';b.onclick=()=>{state.autoPlant=!state.autoPlant;buildButtons()};actionsEl.appendChild(b)}
if(ui.btnNewGame)ui.btnNewGame.onclick=()=>{localStorage.removeItem(SAVE_KEY);state.paused=false;state.inv=new Inventory();state.robots=[];state.tech={robotSpeed:0,yieldBoost:0,harvestRadius:0,routeSlots:0,automation:0};state.selected='plant-wheat';state.camera={x:0,y:0,zoom:1};state.tick=0;state.autoPlant=true;state.grid.tiles=new Uint8Array(W*H);state.grid.crop=Array(W*H).fill(null);state.grid.building=Array(W*H).fill(null);placeInitial();openStartMenu(false);buildButtons();renderShop();save()};
if(ui.btnContinue)ui.btnContinue.onclick=()=>{load();openStartMenu(false);buildButtons();renderShop()};
if(ui.startHint)ui.startHint.textContent='Tipp: Im Shop kannst du Seeds, Gebäude und Tech-Upgrades kaufen.';
renderShop();
if(typeof load==='function'){const _load=load;load=function(){const r=_load();if(ui.btnContinue)ui.btnContinue.disabled=!localStorage.getItem(SAVE_KEY);return r}};
if(typeof save==='function'){const _save=save;save=function(){const r=_save();if(ui.btnContinue)ui.btnContinue.disabled=false;return r}};
